### ISSUE TITLE
Trigger Warning | Light Theme

### ISSUE THREAD

**Issue by mkadirtan** [irnmon/rabbitmq-nestjs-grafana-prometheus-benchmark#2]
Though I prefer light themes, it may trigger a lot of developers. Add a trigger warning or change the default to dark, please.

https://github.com/nullRefErr/monitoring-template/blob/1d9d301858d0f15b95a383df90d16f08d01493a7/docker/grafana/config.ini#L5

**Comment by nullRefErr** [comment]
Changes applied
